//branch.http

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzYwNTU5Mjc5LCJleHAiOjE3NjA1NjA0Nzl9.8IpvzY4yy_Y5_YeGRBqWTZMT4h_mxJ3ASA6ZNwGXOJ4

@baseUrl = http://localhost:3000


### Get all branches
GET {{baseUrl}}/sucursales


### Get branch by ID
GET {{baseUrl}}/sucursales/20


### Create a new branch
POST {{baseUrl}}/sucursales
Content-Type: application/json

{
  "name": "sucursal de prueba",
  "code": "SUC001",
  "address": "Calle 123 #45-67",
  "phone": "1234567890",
  "email": "SUC001@gmail.com",
  "is_active": "ACTIVE"
} 

### update a branch by ID
PATCH {{baseUrl}}/sucursales/1
Content-Type: application/json

{
  "name": "sucursal de prueba editada",
  "code": "SUC02",
  "address": "Calle 123 #45-634",
  "phone": "1234243450",
  "email": "SUC02@gmail.com",
  "is_active": "ACTIVE"
} 

### Delete a branch by ID
DELETE {{baseUrl}}/sucursales/2


### Delete a branch by ID (logical)
DELETE {{baseUrl}}/sucursales/6/logic

### ================== RUTAS CON AUTENTICACIÓN ==================

### Get all branches (with auth)
GET {{baseUrl}}/api/sucursales
Authorization: Bearer {{token}}

### Get branch by ID (with auth)
GET {{baseUrl}}/api/sucursales/9
Authorization: Bearer {{token}} 

### Create a new branch (with auth)
POST {{baseUrl}}/api/sucursales
Authorization: Bearer {{token}}
Content-Type: application/json  

{
  "name": "sucursal usuario 2",
  "code": "sucprueba002",
  "address": "Calle 7 #45-67",
  "phone": "1234567890",
  "email": "pruebas02@gmail.com",
  "is_active": "ACTIVE"
}

### update a branch by ID (with auth)
PATCH {{baseUrl}}/api/sucursales/69
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "sucursal de prueba editada 69",
  "code": "suc69",
  "address": "Calle 1 #45-634",
  "phone": "1234243450",
  "email": "damsss@hotmail.com",
  "is_active": "ACTIVE"
}

### Delete a branch by ID (with auth)
DELETE {{baseUrl}}/api/sucursales/68
Authorization: Bearer {{token}}

### Delete a branch by ID (logical) (with auth)
DELETE {{baseUrl}}/api/sucursales/67/logic
Authorization: Bearer {{token}}



